FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN {{install_command}}
COPY . .
RUN npm run build

FROM {{base_image}}
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE {{port}}
CMD {{start_command}}
