FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml ./
RUN mvn -B -DskipTests dependency:go-offline
COPY . .
RUN {{install_command}}

FROM {{base_image}}
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE {{port}}
CMD {{start_command}}
